---
- hosts: localhost
  connection: local
  vars:
    - controller: 10.zzz.yyy.xxx
      username: admin
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Print Hello
      debug: msg="Hello"

    - name: Print Controller
      debug: msg="{{username}}@{{ controller }}"
